name = "audio-to-midi"
main = "src/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Account ID - you'll need to replace this with your actual Cloudflare account ID
# Get this from your Cloudflare dashboard
# account_id = "your-account-id-here"

[env.production]
name = "audio-to-midi"

[env.staging] 
name = "audio-to-midi-staging"

# Configure static assets - using new format for Wrangler 4.x
[assets]
directory = "./www"
# binding = "ASSETS" # Optional: customize the binding name

# Custom route patterns - routes should be at top level
routes = [
  { pattern = "*audio-to-midi.contrapuntal.cc/*", zone_name = "contrapuntal.cc" }
]

# Variables for the worker
[vars]
ENVIRONMENT = "production"

# Note: Build step removed - using pre-built WASM files
# To rebuild WASM locally, run: npm run build:wasm
